name: aic_mobile
description: AIc - AI companion for teens
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  go_router: ^14.1.0
  flutter_riverpod: ^2.5.1
  dio: ^5.5.0+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.2.2
  firebase_messaging: ^14.9.4
  flutter_local_notifications: ^17.2.3
  just_audio: ^0.9.39
  audio_service: ^0.18.15
  rive: ^0.13.10
  lottie: ^3.1.2
  amplitude_flutter: ^3.13.0
  # RevenueCat
  purchases_flutter: ^6.29.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true



