name: aic_mobile
description: AIc - AI companion for teens (minimal version)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  go_router: ^16.2.2
  flutter_riverpod: ^2.6.1
  dio: ^5.5.0+1
  http: ^1.1.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.2.2
  socket_io_client: ^3.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  logger: ^2.6.1
  url_launcher: ^6.3.1
  lottie: ^3.1.2
  rive: ^0.13.10
  flutter_chat_ui: ^1.6.12
  flutter_chat_types: ^3.6.2
  uuid: ^4.0.0
  firebase_core: ^3.0.0
  firebase_messaging: ^15.0.0
  firebase_analytics: ^11.0.0
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/data/