name: aic_mobile
description: AIc - AI companion for teens
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  go_router: ^16.2.2
  flutter_riverpod: ^2.6.1
  dio: ^5.5.0+1
  http: ^1.1.0
  shared_preferences: ^2.2.2
  socket_io_client: ^3.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.2.2
  firebase_core: ^4.1.0
  firebase_messaging: ^16.0.1
  flutter_local_notifications: ^19.4.2
  timezone: ^0.10.1
  just_audio: ^0.10.5
  audio_service: ^0.18.15
  rive: ^0.13.10
  lottie: ^3.1.2
  amplitude_flutter: ^4.3.7
  # RevenueCat
  purchases_flutter: ^9.6.2
  url_launcher: ^6.3.1
  logger: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/data/


