// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform. '
          'Please run `flutterfire configure` to configure Firebase for your platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDummy_Web_Key_For_Testing_Only_12',
    appId: '1:123456789012:web:abcd1234567890ef',
    messagingSenderId: '123456789012',
    projectId: 'aic-app-temp',
    authDomain: 'aic-app-temp.firebaseapp.com',
    storageBucket: 'aic-app-temp.appspot.com',
    measurementId: 'G-DUMMY123456',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDummy_Android_Key_For_Testing_12_',
    appId: '1:123456789012:android:abcd1234567890ef',
    messagingSenderId: '123456789012',
    projectId: 'aic-app-temp',
    storageBucket: 'aic-app-temp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDummy_iOS_Key_For_Testing_Only_12',
    appId: '1:123456789012:ios:abcd1234567890ef',
    messagingSenderId: '123456789012',
    projectId: 'aic-app-temp',
    storageBucket: 'aic-app-temp.appspot.com',
    iosBundleId: 'com.aic.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDummy_macOS_Key_For_Testing_12___',
    appId: '1:123456789012:ios:abcd1234567890ef',
    messagingSenderId: '123456789012',
    projectId: 'aic-app-temp',
    storageBucket: 'aic-app-temp.appspot.com',
    iosBundleId: 'com.aic.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDummy_Windows_Key_For_Testing_12',
    appId: '1:123456789012:web:abcd1234567890ef',
    messagingSenderId: '123456789012',
    projectId: 'aic-app-temp',
    authDomain: 'aic-app-temp.firebaseapp.com',
    storageBucket: 'aic-app-temp.appspot.com',
    measurementId: 'G-DUMMY123456',
  );
}